EXTERN(osDpGetCounters);
ASSERT(DEFINED(osDpGetCounters), "Error: osDpGetCounters was not linked");

EXTERN(osAiGetStatus);
ASSERT(DEFINED(osAiGetStatus), "Error: osAiGetStatus was not linked");

EXTERN(rmonMain);
ASSERT(DEFINED(rmonMain), "Error: rmonMain was not linked");

EXTERN(osViSetXScale);
ASSERT(DEFINED(osViSetXScale), "Error: osViSetXScale was not linked");

EXTERN(osViSetYScale);
ASSERT(DEFINED(osViSetYScale), "Error: osViSetYScale was not linked");
